name: Build debug kernel
on:
  workflow_dispatch:

jobs:
  
  build-debug-kernel-a14:
    strategy:
      matrix:
        include:
          - version: "6.1"
            sub_level: 75
            os_patch_level: 2024-05
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: android14-${{ matrix.version }}
      version_name: android14-${{ matrix.version }}.${{ matrix.sub_level }}
      tag: android14-${{ matrix.version }}-${{ matrix.os_patch_level }}
      patch_path: ${{ matrix.version }}
      debug: true
